### ISSUE TITLE
USER STORY: Anonimity in polls

### ISSUE THREAD

**Issue by vivienrauch** [vivienrauch/love-running#3]
As a **user** I can **hide my username on the poll** so that **I can post my poll anonimously**.

**Acceptance Criteria**:

- The option should be provided as a checkbox
- The checkbox should not be checked by default
- The option should appear next to the Submit button

**Tasks**:
- [ ] Update the view: the poll design (HTML & CSS) to include the checkbox and show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality

**Comment by vivienrauch** [comment]
This is complete.
